plugins {
    id 'java'
}

repositories {
    mavenCentral()
}

dependencies {
    implementation 'org.slf4j:slf4j-reload4j:2.0.3'
    implementation 'org.seleniumhq.selenium:selenium-java:4.1.2'
    implementation 'com.digy4:digy-runner-core:0.0.55'
    implementation 'com.digy4:digy-runner-cucumber-7:0.0.55'
    implementation 'io.cucumber:cucumber-testng:7.2.3'
}

configurations {
    cucumberRuntime {
        extendsFrom testImplementation
    }
}

group = 'com.digy4'
version = '0.0.1-SNAPSHOT'
description = 'cucumber-testng-selenium-starter'
sourceCompatibility = '11'

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

task digy4DemoCucumberTest() {
    dependsOn assemble, testClasses
    doLast {
        javaexec {
            main = "io.cucumber.core.cli.Main"
            classpath = configurations.cucumberRuntime + sourceSets.main.output + sourceSets.test.output
            args = [
                    '--plugin', 'pretty',
                    '--plugin', 'json:target/cucumber/report.json',
                    '--plugin', 'html:target/cucumber/report.html',
                    '--plugin', 'com.digy4.java.cucumber.Digy4CucumberSupport',
                    '--glue', 'com.digy4.cucumber.steps',
                    '--glue', 'com.digy4.java.cucumber',
                    'src/test/resources/features']
        }
    }
}
